/**
 * A class represents a Match object that is generated by BinaryTrie.longestPrefixMatch.
 * It contains the information of bit sequence and corresponding symbol.
 */
public class Match {
    private BitSequence sequence;
    private Character symbol;
    
    public Match(BitSequence sequence, Character symbol) {
        this.sequence = sequence;
        this.symbol = symbol;
    }

    public Character getSymbol() {
        return this.symbol;
    }

    public BitSequence getSequence() {
        return this.sequence;
    }
}
